using Microsoft.BotBuilderSamples;
using Microsoft.Extensions.FileSystemGlobbing;
using Microsoft.Recognizers.Text.DataTypes.TimexExpression;
using System;
using System.Collections.Generic;

namespace CoreBotCLU
{
  public static class Constants
  {
    public static readonly Dictionary<HumanResource.Intent, string> AnswersForIntent = new Dictionary<HumanResource.Intent, string>
        {
            { HumanResource.Intent._2_WhenEligibleForSickTime,  "Accumulation of sick leave will start at the first day of employment; however, sick leave pay will not be granted until the completion of the 90-day probationary period." },
            { HumanResource.Intent._3_PaidSickTimeForPerDiemEmployee,  "It is the policy of SISU Healthcare Solutions to provide paid sick leave for employees who work a minimum of 40 hours per week." },
            { HumanResource.Intent._4_PaidSickTimeForPartTimeEmployee, "It is the policy of SISU Healthcare Solutions to provide paid sick leave for employees who work a minimum of 40 hours per week." },
            { HumanResource.Intent._5_SickTimePeriod, "Full-time employees who work 40 or more hours per week will receive sick leave at a rate of 40 hours per year. Sick time is loaded into each employee’s sick time bank on January 1st of each year." },
            { HumanResource.Intent._6_SickTimeRollOver, "Sick leave will not be transferred from year to year. Employees on sick leave will not accumulate additional sick leave or vacation pay during the time they are sick. Unused sick leave will be forfeited upon termination." },
            { HumanResource.Intent._7_RestSickTime, "Sick leave will not be transferred from year to year. Employees on sick leave will not accumulate additional sick leave or vacation pay during the time they are sick. Unused sick leave will be forfeited upon termination." },
            { HumanResource.Intent._8_UseSickTimeWhenImmediateFamilySick, "Employees may use sick leave for personal or immediate family illness or accident. The immediate family is defined as spouse, children, mother, and father. Employees will be paid for the actual amount of time they are absent from work, provided it is accrued." },
            { HumanResource.Intent._9_FutureSickTimeUsability, "Sick leave cannot be borrowed in advance. Management may request that an employee provide physician documentation of illness/condition, whether due to the employee's illness or illness of an immediate family member."},
            { HumanResource.Intent._10_VacationTimeAsPartTimeEmployee, "Paid vacation time is for full-time employees during periods of active, full-time, employment." },
            { HumanResource.Intent._11_VacationTimeAsPerDiemEmployee, "Paid vacation time is for full-time employees during periods of active, full-time, employment." },
            { HumanResource.Intent._14_WhenToRequestVacationTime, "Vacation time must be scheduled in writing to the employee’s immediate manager/ supervisor at least one week in advance." },
            { HumanResource.Intent._15_VacationTimeGuaranteed, "The use and duration of vacation time is subject to supervisory approval.  The Company will make every effort to accommodate requests to schedule vacation time but reserves the right to prioritize requests based on business needs, the seniority of the employees requesting vacation time and the good judgment of the supervisor/ manager." },
            { HumanResource.Intent._16_CanTakeOneHourVacation, "If you have completed at least one year of employment, vacation time may be taken in increments as small as one hour. However, vacation time may not be used to compensate employees for tardiness, unexcused absences or for sick time." },
            { HumanResource.Intent._17_CanUseVacationTimeForAbsence, "vacation time may not be used to compensate employees for tardiness, unexcused absences or for sick time." },
            { HumanResource.Intent._19_VacationTimeAfterQuit, "Employees who resign or are terminated, will not be eligible for a payout of vacation time. Vacation days will not be considered as time worked for purposes of calculating overtime. Vacation time cannot be used during a termination notice." },
            { HumanResource.Intent._20_VacationTimeAfterFired, "Employees who resign or are terminated, will not be eligible for a payout of vacation time. Vacation days will not be considered as time worked for purposes of calculating overtime. Vacation time cannot be used during a termination notice." },
            { HumanResource.Intent._21_HolidayOnVacation, "If a holiday occurs during employee’s vacation period, holiday pay will be earned at employee’s regular rate of pay and no vacation time will be used for that day." },
            { HumanResource.Intent._22_AccruedVacationTimeAfterAbsence, "Paid vacation time does not accumulate during an employee’s personal leave of absence or periods of administrative leave." },
            { HumanResource.Intent._23_ManagerResponsibilityUponVacationRequest, "A: Managers are responsible for receiving vacation requests, reviewing and approving or denying them, providing documented confirmation, and monitoring vacation time. They must also inform Payroll of any changes or revisions to approved vacation plans." },
            { HumanResource.Intent._24_CanManagerDenyVacationRequest, "Yes, vacation requests are subject to supervisory approval, and the company reserves the right to prioritize based on business needs and seniority. If a mutually acceptable time cannot be found, the company may decide when you will take your vacation." },
            { HumanResource.Intent._25_HowToScheduleVacationTime, "Vacation requests must be submitted in writing to your immediate manager or supervisor at least one week in advance. Approval of vacation time is subject to the supervisor’s discretion and business needs." },
            { HumanResource.Intent._26_CanVacationTimeCoverTardiness, "No, vacation time cannot be used to compensate for tardiness, unexcused absences, or sick time." },
            { HumanResource.Intent._27_VacationPolicy, "Sisu Healthcare Solutions provides paid vacation for full-time employees who work a minimum of 40 hours per week. Employees earn vacation from their first day of employment, but vacation cannot be used during the probationary period or any extensions. Vacation scheduling requires mutual agreement between employees and their supervisors." },
            { HumanResource.Intent._28_VacationInSmallIncrements, "Yes, vacation can be taken in increments as small as one hour, but cannot be used for tardiness or sick time." },
            {HumanResource.Intent._29_CanHaveAnotherJob, "Work unrelated to the organization’s business would not be improper, nor would most charitable work even though it may be related to the organization’s business."},
            {HumanResource.Intent._30_ImproperJobs, "No employee shall be employed by or perform any services for any competitor, customer, or supplier of the organization, whether or not compensation is received therefore, when such employment or service creates a divided loyalty or the appearance of one. In particular, no employee shall be employed by an outside organization when that employment would involve providing a product or service which the organization has available."},
            {HumanResource.Intent._31_SexuallyHarassed, "SISU Healthcare Solutions does not tolerate harassment, offensive behavior, or intimidation of an employee on any basis including race, color, creed, sex, age, religion, disability, veteran status, marital status, or sexual orientation. Sexual harassment is defined as unwelcome sexual advances, requests for sexual favors, and other verbal or physical conduct of a sexual nature. Sexual harassment may include a range of subtle and not-so-subtle behaviors, and may involve individuals of the same or different gender. These behaviors may include, but is not limited to, unwanted sexual advances, sexual jokes and innuendo, verbal abuse of a sexual nature, comments about an individual’s body, leering, catcalls, touching, obscene gestures and display of sexually suggestive objects or pictures. The inference that sexual favors may have an effect on any condition of employment will not be tolerated. The organization prohibits retaliation against any individual who reports discrimination or harassment, or who investigates such reports."},
            {HumanResource.Intent._32_WhatShouldDo, "Please report to HR immediately."},
            {HumanResource.Intent._33_ProfessionalBoundaries, "Professional boundaries define effective and appropriate interaction between professionals and the public they serve.Boundaries exist to protect both the professional and the patient. Any behavior or interaction which, damages the patient, the professional, and/or the service/care provided is a violation. It is the victimization and exploitation of a patient by the professional. It is a betrayal of the sacred covenant of trust. This includes sexual and non-sexual misconduct. Boundary violations harm the patient and the professional. The ramifications are widespread. Damage usually extends to marriages, families, other patients, communities, clinics, institutions, and the profession in general. The legal environment demands and the public expects strict adherence to professional boundaries. No conscientious professional sets out to violate standards of appropriate, professional relationships with patients, yet violations continue to occur. It can happen to those that are dedicated, moral and highly professional in the overall conduct of their practice. SISU Healthcare Solutions expects its employees to strictly adhere to professional boundaries in their relationship with the patient we serve."},
            {HumanResource.Intent._34_WhereToFindStandardsConduct, "You can find that in document HR-400A"},
            {HumanResource.Intent._35_DrugPolicy, "It is the purpose of SISU Healthcare Solutions to help provide a safe and drug-free work environment for our patients and our employees. With this goal in mind and because of the serious drug abuse problem in today's workplace, we are establishing the following policy for existing and future employees of SISU Healthcare Solutions."},
            {HumanResource.Intent._36_SisuHaveRandomDrugTest, "Yes, employees may be selected at random for drug testing at any interval determined by the organization."},
            {HumanResource.Intent._37_WhatCauseRandomTest, "The organization may ask an employee to submit to a drug test at any time it feels that the employee may be under the influence of drugs or alcohol, including, but not limited to, the following circumstances: evidence of drugs or alcohol on or about the employee's person or in the employee's vicinity, unusual conduct on the employee's part that suggests impairment or influence of drugs or alcohol, negative performance patterns, or excessive and unexplained absenteeism or tardiness."},
            {HumanResource.Intent._38_WhenTestedForDrugs, "Any employee involved in an on-the-job accident or injury under circumstances that suggest possible use or influence of drugs or alcohol in the accident or injury event may be asked to submit to a drug and/or alcohol test.\"Involved in an on-the-job accident or injury\" means not only the one who was injured, but also any employee who potentially contributed to the accident or injury event in any way."},
            {HumanResource.Intent._39_AnyOtherTimes, "Yes, employees may be selected at random for drug testing at any interval determined by the organization."},
            {HumanResource.Intent._40_WhatHappensIfDrugTestFailed, "If an employee is tested for drugs or alcohol outside of the employment context and the results indicate a violation of this policy, the employee may be subject to appropriate disciplinary action, up to and possibly including discharge from employment. In such a case, the employee will be given an opportunity to explain the circumstances prior to any final employment action becoming effective."},
            {HumanResource.Intent._41_HowToReportAnIssue, "An employee may file a grievance if they believe that he or she has not been treated fairly within the guidelines of SISU Healthcare Solutions Policies and Procedures."},
            {HumanResource.Intent._42_HowToFileGrievance, "The employee should bring the problem to the attention of the immediate supervisor for discussion. SISU Healthcare Solutions expects that most problems be resolved at this stage of the procedure. The grievance should be logged on the Concern Form for retrospective review information and performance improvement activity."},
            {HumanResource.Intent._43_WhatIfHavingIssueWithDirectSupervisor, "If the employee feels that a satisfactory solution has not been reached by using either Step 1, that employee may submit a written grievance as follows: • Within five working days of receipt, the President / CEO will contact the employee to review the complaint. • Within five working days of discussing the matter with the employee, the President / CEO will make a decision concerning the grievance and notify the employee and supervisor of the decision."},
            {HumanResource.Intent._44_WhatIfNotOkWithDecision, "If the employee is not satisfied with the President / CEO's decision, or if the grievance is not resolved to the employee’s satisfaction, the employee may request that the grievance be forwarded to the Governing Body for final disposition. Within ten working days of receipt, the Governing body will review the complaint and issue a decision. The decision will be delivered in writing to the employee. The decision of the Governing body is final and binding."},
            {HumanResource.Intent._45_SisuHavePerformanceReview, "Yes.  It is the policy of SISU Healthcare Solutions to have regularly scheduled employee evaluations to assess the performance of job duties. All employees will undergo a performance evaluation by their supervisor at least annually."},
            {HumanResource.Intent._46_PerDiemEmployeeGetReview, "Yes.  It is the policy of SISU Healthcare Solutions to have regularly scheduled employee evaluations to assess the performance of job duties. All employees will undergo a performance evaluation by their supervisor at least annually."},
            {HumanResource.Intent._47_PartTimeEmployeeGetReview, "It is the policy of SISU Healthcare Solutions to have regularly scheduled employee evaluations to assess the performance of job duties. All employees will undergo a performance evaluation by their supervisor at least annually."},
            {HumanResource.Intent._48_ReviewBasedOnWhat, "Performance evaluations are based on the employee's job description and compliance with the pharmacy’s policies and procedures as set forth in the SISU Healthcare Solutions Policies and Procedures Manual and any updates of this document."},
            {HumanResource.Intent._49_IsThereProbationaryPeriod,"Yes. Each new employee will have a 90-day probationary period, after which they will receive a performance evaluation. Full-time employees will be eligible for benefits after the 90-day probationary period. An employee may be terminated without cause during the probationary period"},
            {HumanResource.Intent._50_WhenEligibleForBenefits, "Yes. Full-time employees will be eligible for benefits after the 90-day probationary period."},
            {HumanResource.Intent._51_CanTerminatedWithoutCause, "Yes.  An employee may be terminated without cause during the probationary period"},
            {HumanResource.Intent._52_WhenReceiveSalaryIncrease, "Salary increases may be given at the time the annual evaluation is performed."},
            {HumanResource.Intent._53_ReceiveSalaryIncreaseAfterProbationaryPeriod, "No.  Salary increases are not given at the completion of the 90-day probationary period."},
            {HumanResource.Intent._54_GuaranteedSalaryIncreaseAfterFirstYear, "Salary increases may be given at the time the annual evaluation is performed." },
            {HumanResource.Intent._55_RatingCategoriesForReview, "Categories Include: Outstanding\n Exceeds Expectations\n Meets Expectations\n Needs Improvement\n Not Effective"},
            {HumanResource.Intent._56_PerformanceElements, "Performance Elements Include: Accountability\n Punctuality and Attendance\n Decision Making\n Appearance of Work Area\n Job Knowledge\n Policy and Procedures\n Completion of Assignments\n Cooperation\n Safety Practices\n"},
            {HumanResource.Intent._57_ThingsCauseFired, "The following lists infractions that will warrant employee counseling or termination by his/her supervisor. The list includes, but is not limited to, the following: • Infractions of SISU Healthcare Solutions policy • Misrepresentations of the organization, and/or services • Misuse of SISU Healthcare Solutions resources • Refusing to perform tasks described in the job description • Unauthorized revelation of patient information • Frequent tardiness • Frequent absenteeism • Unexcused absence • Sexual Harassment"},
            {HumanResource.Intent._58_HowManyInfractionsBeforeFired, "Typically, the third infraction may result in termination."},
            {HumanResource.Intent._59_WhatCauseFiredImmediately, "Serious violations of rules and regulations may cause immediate dismissal of employees. Some examples of gross misconduct and violation of rules include, but are not limited to, the following: • Insubordination • Theft • Falsification of records • Fighting • Destruction of property • Intoxication or consumption of controlled substance while on the job • DUI charge with conviction (if it affects the employee's job duties)"},
            {HumanResource.Intent._60_FiredAfterLateTwice, "Upon a second infraction the employee will have another counseling session with his/her supervisor no later than the next working day following the infraction. The counseling session will be recorded on the Employee Counseling Form and signed by the employee and supervisor. The employee will be given a copy of the Employee Counseling Form noting that this is the second infraction. All counseling forms will be stored inside the employee’s Personnel File. The third infraction may result in termination.\n\n *Note: if this is within your 90-day probationary period, you could be terminated."},
            {HumanResource.Intent._61_InfractionsWarrantCounseling, "The following lists infractions that will warrant employee counseling or termination by his/her supervisor. The list includes, but is not limited to, the following: • Infractions of SISU Healthcare Solutions policy • Misrepresentations of the organization, and/or services • Misuse of SISU Healthcare Solutions resources • Refusing to perform tasks described in the job description • Unauthorized revelation of patient information • Frequent tardiness • Frequent absenteeism • Unexcused absence • Sexual Harassment"},
            {HumanResource.Intent._62_WhatIfRefuseDoingSthInJD, "It is the policy of SISU Healthcare Solutions that all employees are to be treated fairly and objectively. Employees will be counseled after his/her first infraction in an attempt to correct inappropriate behavior, not to punish employees. After the first infraction the employee will have a counseling session with his/her supervisor to identify the problem and seek appropriate solutions to resolve the problem. The counseling session will be conducted no later than the next working day following the infraction. The counseling session will be recorded on the Employee Counseling Form and signed by the employee and supervisor."},
            {HumanResource.Intent._63_HowMuchNoticeForQuit, "Employees who intend to terminate employment with SISU Healthcare Solutions, shall provide SISU Healthcare Solutions with at least [two (2) weeks] written notice. Such notice is intended to allow the company time to adjust to the employee’s departure without placing undue burden on those employees who may be required to fill in before a replacement can be found. Since employment with SISU Healthcare Solutions is based on mutual consent, both the employee and SISU Healthcare Solutions have the right to terminate employment at-will, with or without cause, at any time."},
            {HumanResource.Intent._64_PaidAfterFired, "In the case of employee termination, the employee will receive their accrued pay in accordance with all federal, state and local laws."},
            {HumanResource.Intent._65_WhatRequiredToTurnInAfterQuit, "Any employee who terminates employment with SISU Healthcare Solutions shall return all files, records, keys, and any other materials that are the property of SISU Healthcare Solutions."},
            { HumanResource.Intent.None, "Sorry, I am not ready for that question." }
        };
  }
}
